// src/entrypoints/devtools-panel/commands/OpenAbout.svelte
<script lang="ts">
  import { Button } from '$lib/components/ui/button/'
  import * as Dialog from '$lib/components/ui/dialog/'
  import { useEventBus } from '../utils/useEventBus'
  import { version } from '../../../../package.json'
  import copy from 'copy-to-clipboard'
  import { version as esbuildVersion } from 'esbuild-wasm/package.json'
  import { version as monacoVersion } from 'monaco-editor/package.json'
  import { version as typescriptVersion } from 'typescript/package.json'

  let open = false
  useEventBus('openAbout', () => {
    open = true
  })

  let aboutRef: HTMLDivElement | undefined
  async function onCopy() {
    const text = [...aboutRef!.children].map((it) => it.textContent).join('\n')
    console.log('aboutRef?.textContent', text)
    copy(text)
    open = false
  }
</script>

<Dialog.Root {open} onOpenChange={(v) => (open = v)}>
  <Dialog.Content class="sm:max-w-[425px]">
    <Dialog.Header>
      <Dialog.Title>About</Dialog.Title>
    </Dialog.Header>
    <div bind:this={aboutRef}>
      <div>Version: {version}</div>
      <div>Copyright © 2024 rxliuli</div>
      <div>TypeScript: {typescriptVersion}</div>
      <div>Monaco-Editor: {monacoVersion}</div>
      <div>ESBuild: {esbuildVersion}</div>
    </div>
    <Dialog.Footer>
      <Button on:click={onCopy}>Copy</Button>
    </Dialog.Footer>
  </Dialog.Content>
</Dialog.Root>

// entrypoints/devtools-panel/commands/OpenAbout.tsx
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { useEventBus } from '../utils/useEventBus'
import copy from 'copy-to-clipboard'
import esbuildPkg from 'esbuild-wasm/package.json'
import monacoPkg from 'monaco-editor/package.json'
import typescriptPkg from 'typescript/package.json'
import { version } from '../../../package.json'

export function OpenAbout() {
  const [open, setOpen] = useState(false)

  useEventBus('openAbout', () => {
    setOpen(true)
  })

  const handleCopy = async () => {
    const text = [
      `Version: ${version}`,
      'Copyright © 2024 rxliuli',
      `TypeScript: ${typescriptPkg.version}`,
      `Monaco-Editor: ${monacoPkg.version}`,
      `ESBuild: ${esbuildPkg.version}`,
    ].join('\n')

    console.log('aboutRef?.textContent', text)
    copy(text)
    setOpen(false)
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>About</DialogTitle>
        </DialogHeader>
        <div>
          <div>Version: {version}</div>
          <div>Copyright © 2024 rxliuli</div>
          <div>TypeScript: {typescriptPkg.version}</div>
          <div>Monaco-Editor: {monacoPkg.version}</div>
          <div>ESBuild: {esbuildPkg.version}</div>
        </div>
        <DialogFooter>
          <Button onClick={handleCopy}>Copy</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
