// entrypoints/devtools-panel/Editor.tsx
import { useEffect, useRef, useState } from 'react'
import type * as Monaco from 'monaco-editor/esm/vs/editor/editor.api'
import { initialize } from 'esbuild-wasm'
import wasmUrl from 'esbuild-wasm/esbuild.wasm?url'
import { toast } from 'sonner'
import { serializeError } from 'serialize-error'
import type { typeAcquisition } from './utils/initTypeAcquisition'
import TypeAcquisitionWorker from './utils/initTypeAcquisition?worker'
import FormatCodeWorker from './utils/formatCode?worker'
import type { formatCode } from './utils/formatCode'
import { wrap, proxy } from 'comlink'
import { useExecutionStore } from './store'
import { useEventBus } from './utils/useEventBus'
import { useTheme } from 'next-themes'
import { useMount } from 'react-use'
import { bundle } from './utils/bundle'

const STORAGE_KEY = 'devtools-editor-content'

function saveEditorContent(editor: Monaco.editor.IStandaloneCodeEditor | null) {
  if (editor) {
    const content = editor.getValue()
    localStorage.setItem(STORAGE_KEY, content)
  }
}

function loadEditorContent(): string {
  return (
    localStorage.getItem(STORAGE_KEY) ||
    '// Cmd/Ctrl+S to execute\n' +
      "console.log('Hello from Monaco!')\n" +
      '// Add breakpoint in the line above to debug\n' +
      '// debugger'
  )
}

export function Editor() {
  const editorContainerRef = useRef<HTMLDivElement>(null)
  const editorRef = useRef<Monaco.editor.IStandaloneCodeEditor | null>(null)
  const monacoRef = useRef<typeof Monaco | null>(null)
  const [isInit, setIsInit] = useState(false)
  const { resolvedTheme } = useTheme()

  const executionStore = useExecutionStore()

  const compileCode = async (code: string, controller: AbortController) => {
    if (!isInit) {
      try {
        await initialize({
          wasmURL: wasmUrl,
        })
      } catch (error) {
        if (
          serializeError(error as Error).message !==
          'Cannot call "initialize" more than once'
        ) {
          throw error
        }
      }
      setIsInit(true)
    }
    return await bundle(code, {
      signal: controller.signal,
    })
  }

  const injectAndExecuteCode = async (code: string) => {
    return new Promise<void>((resolve, reject) => {
      // TODO: not working with Safari
      browser.devtools.inspectedWindow.eval(
        code,
        (_result: any, isException: any) => {
          if (isException) {
            reject(new Error(isException.value || 'Evaluation failed'))
          } else {
            resolve()
          }
        },
      )
    })
  }

  const execute = async () => {
    if (executionStore.isExecuting) {
      executionStore.stop()
      toast.info('Execution cancelled')
      return
    }

    const controller = new AbortController()
    executionStore.start(controller)
    try {
      await editorRef.current?.getAction('editor.action.formatDocument')?.run()
      const buildCode = await compileCode(
        editorRef.current?.getValue() || '',
        controller,
      )
      console.log('buildCode', buildCode)
      await injectAndExecuteCode(buildCode)
      toast.success('Code executed successfully')
    } catch (error) {
      if (error instanceof Error && error.message.includes('Abort')) {
        toast.info('Execution aborted')
      } else {
        console.error('Error:', error)
        toast.error('Compilation Error', {
          description: serializeError(error as Error).message,
          duration: 10000,
        })
      }
    } finally {
      executionStore.stop()
    }
  }

  function updateEditorTheme(theme?: string) {
    const editorTheme = theme === 'dark' ? 'vs-dark' : 'vs'
    console.log('updateEditorTheme', editorTheme, editorRef.current)
    if (editorRef.current) {
      editorRef.current.updateOptions({
        theme: editorTheme,
      })
    }
  }

  // Initialize Monaco Editor
  useMount(() => {
    let mounted = true

    const initializeEditor = async () => {
      if (!editorContainerRef.current) return

      const monaco = (await import('./monaco')).monaco
      if (!mounted) return

      monacoRef.current = monaco
      monaco.editor.addKeybindingRules([
        {
          keybinding: monaco.KeyCode.F12,
          command: null,
        },
      ])
      const defaults = monaco.languages.typescript.typescriptDefaults
      defaults.setCompilerOptions({
        target: monaco.languages.typescript.ScriptTarget.ESNext,
        allowNonTsExtensions: true,
        moduleResolution:
          monaco.languages.typescript.ModuleResolutionKind.NodeJs,
        module: monaco.languages.typescript.ModuleKind.ESNext,
        jsx: monaco.languages.typescript.JsxEmit.Preserve,
        noEmit: true,
        strict: true,
        esModuleInterop: true,
      })
      defaults.setDiagnosticsOptions({ diagnosticCodesToIgnore: [1375] })
      monaco.languages.registerDocumentFormattingEditProvider('typescript', {
        provideDocumentFormattingEdits: async (model, _options, token) => {
          const worker = new FormatCodeWorker()
          const f = wrap<typeof formatCode>(worker)
          const formattedCode = await f(model.getValue(), 0)
          return [
            {
              text: formattedCode.formatted,
              range: model.getFullModelRange(),
            },
          ]
        },
      })

      const initialTheme = resolvedTheme === 'dark' ? 'vs-dark' : 'vs'
      const editor = monaco.editor.create(editorContainerRef.current, {
        language: 'typescript',
        theme: initialTheme,
        fontSize: 14,
        automaticLayout: true,
        minimap: { enabled: false },
        scrollBeyondLastLine: false,
        wordWrap: 'on',
        tabSize: 2,
        insertSpaces: true,
      })

      if (!mounted) {
        editor.dispose()
        return
      }

      editorRef.current = editor
      const model = monaco.editor.createModel(
        loadEditorContent(),
        'typescript',
        monaco.Uri.file('example.tsx'),
      )
      editor.setModel(model)

      const worker = new TypeAcquisitionWorker()
      const ta = wrap<typeof typeAcquisition>(worker)
      await ta.init(proxy(addLibraryToRuntime))

      // 添加内容变化监听器
      editor.onDidChangeModelContent(async () => {
        saveEditorContent(editor)
        // 判断是否有错误
        const value = editor.getValue()
        await ta.dl(value)
      })

      // 添加编辑器特定的键盘事件监听器
      editor.onKeyDown(handleKeyDown)

      // editor 初始化完成后，执行一次 ta
      ta.dl(editor.getValue())

      function addLibraryToRuntime(code: string, _path: string) {
        const path = 'file://' + _path
        defaults.addExtraLib(code, path)
        console.log(`[ATA] Adding ${path} to runtime`, { code })
      }
    }

    initializeEditor()

    return () => {
      mounted = false
      if (monacoRef.current) {
        monacoRef.current.editor.getModels().forEach((model) => model.dispose())
      }
      if (editorRef.current) {
        saveEditorContent(editorRef.current)
        editorRef.current.dispose()
        editorRef.current = null
      }
    }
  })

  // Theme change effect
  useEffect(() => {
    updateEditorTheme(resolvedTheme)
  }, [resolvedTheme])

  // Event listeners - setup once on mount
  const handleResize = () => {
    editorRef.current?.layout()
  }
  function handleKeyDown(event: KeyboardEvent | Monaco.IKeyboardEvent) {
    if ((event.ctrlKey || event.metaKey) && event.code === 'KeyS') {
      event.preventDefault()
      event.stopPropagation()
      execute()
    }
  }
  useMount(() => {
    window.addEventListener('resize', handleResize)
    window.addEventListener('keydown', handleKeyDown)

    return () => {
      window.removeEventListener('resize', handleResize)
      window.removeEventListener('keydown', handleKeyDown)
    }
  })

  // Event bus listeners
  useEventBus('runScript', execute)
  useEventBus('changeFontSize', (fontSize) => {
    editorRef.current?.updateOptions({ fontSize })
  })

  return <div className="w-full h-full flex-1" ref={editorContainerRef} />
}

// src/entrypoints/devtools-panel/Editor.svelte
<script lang="ts">
  import { onDestroy, onMount } from 'svelte'
  import type * as Monaco from 'monaco-editor/esm/vs/editor/editor.api'
  import { transform, initialize } from 'esbuild-wasm'
  import wasmUrl from 'esbuild-wasm/esbuild.wasm?url'
  import { toast } from 'svelte-sonner'
  import { serializeError } from 'serialize-error'
  import type { transformImports } from './utils/transformImports'
  import TransformImportsWorker from './utils/transformImports?worker'
  import type { transformAsync } from './utils/transformAsync'
  import TransformAsyncWorker from './utils/transformAsync?worker'
  import type { typeAcquisition } from './utils/initTypeAcquisition'
  import TypeAcquisitionWorker from './utils/initTypeAcquisition?worker'
  import FormatCodeWorker from './utils/formatCode?worker'
  import type { formatCode } from './utils/formatCode'
  import { wrap, proxy } from 'comlink'
  import { settings } from './store'
  import { useEventBus } from './utils/useEventBus'
  import { get } from 'svelte/store'
  import { mode } from 'mode-watcher'
  import { watch } from './utils/watch'
  import { location } from 'vfile-location'

  let editor: Monaco.editor.IStandaloneCodeEditor
  let monaco: typeof Monaco
  let editorContainer: HTMLElement

  const STORAGE_KEY = 'devtools-editor-content'

  function saveEditorContent() {
    if (editor) {
      const content = editor.getValue()
      localStorage.setItem(STORAGE_KEY, content)
    }
  }

  function loadEditorContent(): string {
    return (
      localStorage.getItem(STORAGE_KEY) ||
      '// Cmd/Ctrl+S to execute\n' +
        "console.log('Hello from Monaco!')\n" +
        '// Add breakpoint in the line above to debug\n' +
        '// debugger'
    )
  }

  let isInit = false

  async function compileCode(code: string) {
    if (!isInit) {
      try {
        await initialize({
          wasmURL: wasmUrl,
        })
      } catch (error) {
        if (
          serializeError(error).message !==
          'Cannot call "initialize" more than once'
        ) {
          throw error
        }
      }
      isInit = true
    }
    if (code.includes('import')) {
      const worker = new TransformImportsWorker()
      const f = wrap<typeof transformImports>(worker)
      code = await f(code)
    } else {
      const worker = new TransformAsyncWorker()
      const f = wrap<typeof transformAsync>(worker)
      code = await f(code)
    }
    const result = await transform(code, {
      loader: 'tsx',
      sourcemap: 'inline',
      format: 'iife',
      jsx: 'transform',
      jsxFactory: 'h',
      jsxFragment: 'Fragment',
      target: 'esnext',
    })
    return result.code
  }

  async function execute() {
    try {
      await editor.getAction('editor.action.formatDocument')?.run()
      const buildCode = await compileCode(editor.getValue())
      console.log('buildCode', buildCode)
      await injectAndExecuteCode(buildCode)
      toast.success('Code executed successfully')
    } catch (error) {
      console.error('Error:', error)
      toast.error('Compilation Error', {
        description: serializeError(error).message,
        duration: 10000, // 显示10秒
        style:
          'background: #FEF2F2; color: #991B1B; border: 1px solid #F87171;',
      })
    }
  }

  async function handleKeyDown(event: KeyboardEvent) {
    if ((event.ctrlKey || event.metaKey) && event.key === 's') {
      event.preventDefault()
      await execute()
    }
  }

  async function injectAndExecuteCode(code: string) {
    // 使用 Chrome DevTools 协议注入并执行代码
    const [, isException] = await browser.devtools.inspectedWindow.eval(code)
    if (isException && isException.isException) {
      throw new Error(isException.value)
    }
  }

  function detectTheme(): 'vs' | 'vs-dark' {
    return get(mode) === 'dark' ? 'vs-dark' : 'vs'
  }

  function updateEditorTheme() {
    const theme = detectTheme()
    console.log('updateEditorTheme', theme, editor)
    if (editor) {
      editor.updateOptions({
        theme,
      })
    }
  }

  function handleResize() {
    editor.layout()
  }

  onMount(async () => {
    const monaco = (await import('./monaco')).monaco
    const defaults = monaco.languages.typescript.typescriptDefaults
    defaults.setCompilerOptions({
      target: monaco.languages.typescript.ScriptTarget.ESNext,
      allowNonTsExtensions: true,
      moduleResolution: monaco.languages.typescript.ModuleResolutionKind.NodeJs,
      module: monaco.languages.typescript.ModuleKind.ESNext,
      jsx: monaco.languages.typescript.JsxEmit.Preserve,
      noEmit: true,
      strict: true,
      esModuleInterop: true,
    })
    defaults.setDiagnosticsOptions({ diagnosticCodesToIgnore: [1375] })
    monaco.languages.registerDocumentFormattingEditProvider('typescript', {
      provideDocumentFormattingEdits: async (model, _options, token) => {
        const worker = new FormatCodeWorker()
        const f = wrap<typeof formatCode>(worker)
        const formattedCode = await f(model.getValue(), 0)
        return [
          {
            text: formattedCode.formatted,
            range: model.getFullModelRange(),
          },
        ]
      },
    })

    const initialTheme = detectTheme()
    editor = monaco.editor.create(editorContainer, {
      language: 'typescript',
      theme: initialTheme,
      fontSize: get(settings).fontSize,
    })
    const model = monaco.editor.createModel(
      loadEditorContent(),
      'typescript',
      monaco.Uri.file('example.tsx'),
    )
    editor.setModel(model)

    const worker = new TypeAcquisitionWorker()
    const ta = wrap<typeof typeAcquisition>(worker)
    await ta.init(proxy(addLibraryToRuntime))

    // 添加内容变化监听器
    editor.onDidChangeModelContent(async () => {
      saveEditorContent()
      // 判断是否有错误
      const value = editor.getValue()
      await ta.dl(value)
    })
    // editor 初始化完成后，执行一次 ta
    ta.dl(editor.getValue())

    function addLibraryToRuntime(code: string, _path: string) {
      const path = 'file://' + _path
      defaults.addExtraLib(code, path)
      console.log(`[ATA] Adding ${path} to runtime`, { code })
    }
    // 添加键盘事件监听器
    window.addEventListener('keydown', handleKeyDown)

    // 添加窗口尺寸变化监听器
    window.addEventListener('resize', handleResize)
  })

  // 添加主题变化监听器
  watch(mode, updateEditorTheme)

  onDestroy(() => {
    monaco?.editor.getModels().forEach((model) => model.dispose())
    editor?.dispose()
    // 移除键盘事件监听器
    window.removeEventListener('keydown', handleKeyDown)

    window.removeEventListener('resize', handleResize)

    // 保存编辑器内容
    saveEditorContent()
  })

  useEventBus('runScript', execute)
  useEventBus('changeFontSize', (fontSize) => {
    editor.updateOptions({ fontSize })
  })
</script>

<div class="w-full h-full flex-1" bind:this={editorContainer} />
