// entrypoints/devtools-panel/Toolbar.tsx
import {
  Menubar,
  MenubarContent,
  MenubarItem,
  MenubarMenu,
  MenubarTrigger,
} from '@/components/ui/menubar'
import { em, useExecutionStore } from './store'
import { PlayIcon, Loader2Icon } from 'lucide-react'
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip'
import { Button } from '@/components/ui/button'

export function Toolbar() {
  const isExecuting = useExecutionStore((s) => s.isExecuting)
  const stop = useExecutionStore((s) => s.stop)

  const getIcon = () => {
    if (isExecuting) {
      return (
        <Button size="icon" variant="destructive">
          <Loader2Icon className="w-4 h-4 animate-spin text-muted-foreground" />
        </Button>
      )
    }
    return <PlayIcon className="w-4 h-4" />
  }

  const getTooltipText = () => {
    return isExecuting ? 'Stop execution' : 'Run ⌘S'
  }

  return (
    <Menubar className="toolbar">
      <MenubarMenu>
        <MenubarTrigger>TypeScript Console</MenubarTrigger>
        <MenubarContent>
          <MenubarItem onClick={() => em.emit('openAbout')}>About</MenubarItem>
          <MenubarItem onClick={() => em.emit('openSettings')}>
            Settings
          </MenubarItem>
        </MenubarContent>
      </MenubarMenu>
      <MenubarMenu>
        <MenubarTrigger asChild={true}>
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  size="icon"
                  variant="ghost"
                  onClick={() => (isExecuting ? stop() : em.emit('runScript'))}
                  disabled={false}
                >
                  {getIcon()}
                </Button>
              </TooltipTrigger>
              <TooltipContent>
                <p>{getTooltipText()}</p>
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
        </MenubarTrigger>
      </MenubarMenu>
    </Menubar>
  )
}

// src/entrypoints/devtools-panel/Toolbar.svelte
<script lang="ts">
  import * as Menubar from '$lib/components/ui/menubar'
  import { em } from './store'
  import { PlayIcon } from 'lucide-svelte'
  import * as Tooltip from '$lib/components/ui/tooltip'
  import Button from '$lib/components/ui/button/button.svelte'
</script>

<Menubar.Root class="toolbar">
  <Menubar.Menu>
    <Menubar.Trigger>TypeScript Console</Menubar.Trigger>
    <Menubar.Content>
      <Menubar.Item on:click={() => em.emit('openAbout')}>About</Menubar.Item>
      <Menubar.Item on:click={() => em.emit('openSettings')}
        >Settings</Menubar.Item
      >
    </Menubar.Content>
  </Menubar.Menu>
  <Menubar.Menu>
    <Menubar.Item on:click={() => em.emit('runScript')}>
      <Tooltip.Root>
        <Tooltip.Trigger asChild let:builder>
          <Button size="icon" variant="ghost" builders={[builder]}>
            <PlayIcon class="w-4 h-4" />
          </Button>
        </Tooltip.Trigger>
        <Tooltip.Content>
          <p>Run ⌘S</p>
        </Tooltip.Content>
      </Tooltip.Root>
    </Menubar.Item>
  </Menubar.Menu>
</Menubar.Root>
